//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artevol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid
    {
        public int id { get; set; }
        public Nullable<int> prd_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
