//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artevol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_prd = new HashSet<order_prd>();
        }
    
        public int id { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public string payment_type { get; set; }
        public Nullable<int> tr_id { get; set; }
        public string tr_img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_prd> order_prd { get; set; }
        public virtual user user1 { get; set; }
    }
}
