//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artevol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_prd
    {
        public int id { get; set; }
        public int order { get; set; }
        public int product { get; set; }
        public int quantity { get; set; }
    
        public virtual product product1 { get; set; }
        public virtual order order1 { get; set; }
    }
}
