//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artevol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int id { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<int> reqType { get; set; }
        public string status { get; set; }
        public string desc { get; set; }
        public string email { get; set; }
    
        public virtual reqType reqType1 { get; set; }
        public virtual user user1 { get; set; }
    }
}
